# Generated by Django 4.2.23 on 2025-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('producer', 'Producer'), ('manufacturer', 'Manufacturer'), ('seller', 'Seller'), ('mixed', 'Mixed')], default='', max_length=50),
        ),
    ]
