# Generated by Django 4.2.23 on 2025-06-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='machine_id',
        ),
    ]
