# Generated by Django 4.1.1 on 2025-07-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_product_machine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineprocesslist',
            name='process',
        ),
        migrations.AddField(
            model_name='machineprocesslist',
            name='process_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='Backend.processtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(choices=[('meat', 'Meat'), ('dairy', 'Dairy'), ('fish', 'Fish'), ('honey & marmalade', 'Honey & Marmalade'), ('fruit & vegetables', 'Fruit & Vegetables'), ('pasta & other', 'Pasta & Other'), ('oil', 'Oil'), ('beverages', 'Beverages'), ('eggs', 'Eggs'), ('salt & herbs', 'Salt & Herbs'), ('tofu', 'Tofu')], max_length=255),
        ),
    ]
