# Generated by Django 4.1.1 on 2025-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_machineprocesslist_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(default='somthing', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='chain_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
