# Generated by Django 4.1.1 on 2025-07-21 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_product_batch_number_product_chain_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocesslist',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprocesslist',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
