# Generated by Django 4.1.1 on 2025-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_productprocesslist_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
    ]
